<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>TuiVision.Examples.Videomode</RootNamespace>
    <AssemblyName>Videomode</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TuiVision.Core\TuiVision.Core.csproj" />
    <ProjectReference Include="..\..\src\TuiVision.Controls\TuiVision.Controls.csproj" />
    <ProjectReference Include="..\..\src\TuiVision.Drivers.Console\TuiVision.Drivers.Console.csproj" />
  </ItemGroup>
</Project>
