<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TuiVision.Core\TuiVision.Core.csproj" />
    <ProjectReference Include="..\TuiVision.Drivers.Console\TuiVision.Drivers.Console.csproj" />
    <ProjectReference Include="..\TuiVision.Serialization\TuiVision.Serialization.csproj" />
  </ItemGroup>

</Project>
